// GLOBAL //
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_TAGS = "FETCH_TAGS";
export const FETCH_SKILLS = "FETCH_SKILLS";
export const TOGGLE_POPUP = "TOGGLE_POPUP";
export const SET_EDITED_ROOM = "SET_EDITED_ROOM";
export const FETCH_SUGGESTIONS = "FETCH_SUGGESTIONS";



// ROOMS //
export const NEW_ROOM = "NEW_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";
export const EDIT_ROOM = "EDIT_ROOM";

// EXPLORE //
export const FETCH_NEW_EXPLORE = "FETCH_NEW_EXPLORE";
export const FETCH_MORE_EXPLORE = "FETCH_MORE_EXPLORE";

// FAVORITES //
export const FETCH_NEW_FAVORITES = "FETCH_NEW_FAVORITES";
export const FETCH_MORE_FAVORITES = "FETCH_MORE_FAVORITES";

// PRIVATE //
export const FETCH_NEW_PRIVATE = "FETCH_NEW_PRIVATE";
export const FETCH_MORE_PRIVATE = "FETCH_MORE_PRIVATE";

// PUBLIC //
export const FETCH_NEW_PUBLIC = "FETCH_NEW_PUBLIC";
export const FETCH_MORE_PUBLIC = "FETCH_MORE_PUBLIC";

// MY PUBLIC FLOORS //
export const FETCH_NEW_PUBLIC_FLOORS = "FETCH_NEW_PUBLIC_FLOORS";
export const FETCH_MORE_PUBLIC_FLOORS = "FETCH_MORE_PUBLIC_FLOORS";
export const ADD_PUBLIC_FLOOR = "ADD_PUBLIC_PUBLIC_FLOOR";

// MY PRIVATE FLOORS //
export const FETCH_NEW_PRIVATE_FLOORS = "FETCH_NEW_PRIVATE_FLOORS";
export const FETCH_MORE_PRIVATE_FLOORS = "FETCH_MORE_PRIVATE_FLOORS";
export const ADD_PRIVATE_FLOOR = "ADD_PUBLIC_PRIVATE_FLOOR";



// MY ROOMS //
export const FETCH_NEW_MY_ROOMS = "FETCH_NEW_MY_ROOMS";
export const FETCH_MORE_MY_ROOMS = "FETCH_MORE_MY_ROOMS";

// FLOORS //
export const FETCH_NEW_EXPLORE_FLOORS = "FETCH_NEW_EXPLORE_FLOORS";
export const FETCH_MORE_EXPLORE_FLOORS = "FETCH_MORE_EXPLORE_FLOORS";

// SEARCHED LIVE //
export const FETCH_NEW_SEARCHED = "FETCH_NEW_SEARCHED";
export const FETCH_MORE_SEARCHED = "FETCH_MORE_SEARCHED";

// STRANGER PROFILE //
export const FETCH_STRANGER_PROFILE = "FETCH_STRANGER_PROFILE";

// USER //
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const FETCH_UPDATES = "FETCH_UPDATES";
export const FETCH_BACKSTAGE = "FETCH_BACKSTAGE";

export const ADD_UPDATES_NOTIFICATION = "ADD_UPDATES_NOTIFICATION";
export const RESET_UPDATES_NOTIFICATIONS = "RESET_UPDATES_NOTIFICATIONS";

export const ADD_BACKSTAGE_NOTIFICATION = "ADD_BACKSTAGE_NOTIFICATION";
export const RESET_BACKSTAGE_NOTIFICATIONS = "RESET_BACKSTAGE_NOTIFICATIONS";

export const RESET_NOTIFICATIONS = "RESET_BACKSTAGE_NOTIFICATIONS";

// CHANNELS //
export const SET_CHANNELS = "SET_CHANNELS";
export const ADD_CHANNEL = "ADD_CHANNEL";
export const REMOVE_CHANNEL = "REMOVE_CHANNEL";

// EVENTS //
export const FETCH_EVENTS = "FETCH_EVENTS";
export const ADD_EVENT = "ADD_EVENT";
export const REMOVE_EVENT = "REMOVE_EVENT";

// FLOORS //
export const SET_FLOORS = "SET_FLOORS";
export const DELETE_FLOOR = "DELETE_FLOOR";
export const EDIT_FLOOR = "EDIT_FLOOR";
export const REMOVE_FLOOR = "REMOVE_FLOOR";

export const SET_CURRENT_FLOOR = "SET_CURRENT_FLOOR";

export const SET_FLOOR_PLANS = "SET_FLOOR_PLANS";

// CAREERS //
export const FETCH_POSITIONS = "FETCH_POSITIONS";
export const FETCH_SINGLE_POSITION = "FETCH_SINGLE_POSITION";

// BLOG //
export const FETCH_NEW_BLOG_POSTS = "FETCH_NEW_BLOG_POSTS";
export const FETCH_MORE_BLOG_POSTS = "FETCH_MORE_BLOG_POSTS";
export const NEW_POST = "NEW_POST";
export const DELETE_POST = "DELETE_POST";
export const EDIT_POST = "EDIT_POST";
