// GLOBAL //
export const FETCH_TAGS = "FETCH_TAGS";
export const TOGGLE_POPUP = "TOGGLE_POPUP";
export const SET_PAGE = "SET_PAGE";
export const SET_EDITED_STREAM = "SET_EDITED_STREAM";

// STREAMS // 
export const FETCH_NEW_STREAMS = "FETCH_NEW_STREAMS";
export const FETCH_MORE_STREAMS = "FETCH_MORE_STREAMS";
export const NEW_STREAM = "NEW_STREAM";
export const DELETE_STREAM = "DELETE_STREAM";
export const EDIT_STREAM = "EDIT_STREAM";

// CALENDAR //
export const FETCH_NEW_CALENDAR = "FETCH_NEW_CALENDAR";
export const FETCH_MORE_CALENDAR = "FETCH_MORE_CALENDAR";
export const ADD_TO_CALENDAR = "ADD_TO_CALENDAR";
export const REMOVE_FROM_CALENDAR = "REMOVE_FROM_CALENDAR";
export const EDIT_CALENDAR = "EDIT_CALENDAR";


// MY STREAMS //
export const FETCH_MY_STREAMS = "FETCH_MY_STREAMS";
export const DELETE_MY_STREAMS = "DELETE_MY_STREAMS";
export const ADD_MY_STREAMS = "ADD_MY_STREAMS";
export const EDIT_MY_STREAMS = "EDIT_MY_STREAMS";
