// GLOBAL //
export const FETCH_TAGS = "FETCH_TAGS";
export const TOGGLE_POPUP = "TOGGLE_POPUP";
export const SET_PAGE = "SET_PAGE";
export const SET_EDITED_STREAM = "SET_EDITED_STREAM";

// ALL STREAMS //
export const NEW_STREAM_LIVE = "NEW_STREAM_LIVE";
export const NEW_STREAM_UPCOMING = "NEW_STREAM_UPCOMING";
export const DELETE_STREAM = "DELETE_STREAM";
export const EDIT_STREAM = "EDIT_STREAM";

//EXPLORE LIVE //
export const FETCH_NEW_EXPLORE_LIVE = "FETCH_NEW_EXPLORE_LIVE";
export const FETCH_MORE_EXPLORE_LIVE = "FETCH_MORE_EXPLORE_LIVE";
export const NEW_EXPLORE_LIVE = "NEW_STREAM_LIVE";

// EXPLORE UPCOMING //
export const FETCH_NEW_EXPLORE_UPCOMING = "FETCH_NEW_EXPLORE_UPCOMING";
export const FETCH_MORE_EXPLORE_UPCOMING = "FETCH_MORE_EXPLORE_UPCOMING";

// SUBSCRIPTIONS LIVE //
export const FETCH_NEW_SUBSCRIPTIONS_LIVE = "FETCH_NEW_SUBSCRIPTIONS_LIVE";
export const FETCH_MORE_SUBSCRIPTIONS_LIVE = "FETCH_MORE_SUBSCRIPTIONS_LIVE";

// SUBSCRIPTIONS UPCOMING //
export const FETCH_NEW_SUBSCRIPTIONS_UPCOMING = "FETCH_NEW_SUBSCRIPTIONS_UPCOMING";
export const FETCH_MORE_SUBSCRIPTIONS_UPCOMING = "FETCH_MORE_SUBSCRIPTIONS_UPCOMING";

// CALENDAR ALL //
export const REMOVE_FROM_CALENDAR = "REMOVE_FROM_CALENDAR";

// CALENDAR LIVE //
export const FETCH_NEW_CALENDAR_LIVE = "FETCH_NEW_CALENDAR_LIVE";
export const FETCH_MORE_CALENDAR_LIVE = "FETCH_MORE_CALENDAR_LIVE";
export const ADD_TO_CALENDAR_LIVE = "ADD_TO_CALENDAR_LIVE";

// CALENDAR UPCOMING //
export const FETCH_NEW_CALENDAR_UPCOMING = "FETCH_NEW_CALENDAR_UPCOMING";
export const FETCH_MORE_CALENDAR_UPCOMING = "FETCH_MORE_CALENDAR_UPCOMING";
export const ADD_TO_CALENDAR_UPCOMING = "ADD_TO_CALENDAR_UPCOMING";

// CALENDAR PAST //
export const FETCH_NEW_CALENDAR_PAST = "FETCH_NEW_CALENDAR_PAST";
export const FETCH_MORE_CALENDAR_PAST = "FETCH_MORE_CALENDAR_PAST";

// MINE LIVE //
export const FETCH_NEW_MINE_LIVE = "FETCH_NEW_MINE_LIVE";
export const FETCH_MORE_MINE_LIVE = "FETCH_PAST_MINE_LIVE";

// MINE UPCOMING //
export const FETCH_NEW_MINE_UPCOMING = "FETCH_NEW_MINE_UPCOMING";
export const FETCH_MORE_MINE_UPCOMING = "FETCH_PAST_MINE_UPCOMING";

// MINE PAST //
export const FETCH_NEW_MINE_PAST = "FETCH_NEW_MINE_PAST";
export const FETCH_MORE_MINE_PAST = "FETCH_PAST_MINE_PAST";


// SEARCHED LIVE //
export const FETCH_NEW_SEARCHED_STREAMS_LIVE =
  "FETCH_NEW_SEARCHED_STREAMS_LIVE";
export const FETCH_MORE_SEARCHED_STREAMS_LIVE =
  "FETCH_MORE_SEARCHED_STREAMS_LIVE";

// SEARCHED UPCOMING //
export const FETCH_NEW_SEARCHED_STREAMS_UPCOMING = "FETCH_NEW_SEARCHED_STREAMS_UPCOMING";
export const FETCH_MORE_SEARCHED_STREAMS_UPCOMING = "FETCH_MORE_SEARCHED_STREAMS_UPCOMING";

// TEMPLATES //
export const FETCH_TEMPLATES = "FETCH_TEMPLATES";
export const NEW_TEMPLATE = "NEW_TEMPLATE";
export const DELETE_TEMPLATE = "DELETE_TEMPLATE";
